// index.js
export const projects = [
  {
    id: 1,
    name: "Classic Collection",
    description: "Clean white background with bold LEGO-style typography. Perfect for a timeless, iconic collector display.",
    href: "/customizer?template=classic",
    image: "/assets/projects/mobile-accessories-store.jpg",
    bgImage: "/assets/backgrounds/blanket.jpg",
    frameworks: [
      { id: 1, name: "Portrait" },
      { id: 2, name: "Minimalist" },
      { id: 3, name: "Custom Text" },
      { id: 4, name: "Auto-Sized" },
    ],
  },
  {
    id: 2,
    name: "Hero Showcase",
    description: "Large character artwork with dramatic lighting and a dark border. Make your minifig the star of the show.",
    href: "/customizer?template=hero",
    image: "/assets/projects/plant-shop.jpg",
    bgImage: "/assets/backgrounds/curtains.jpg",
    frameworks: [
      { id: 1, name: "Portrait" },
      { id: 2, name: "Bold" },
      { id: 3, name: "Image Upload" },
      { id: 4, name: "Auto-Sized" },
    ],
  },
  {
    id: 3,
    name: "Series Archive",
    description: "Display set number, series name, year, and piece count. The ultimate card for serious collectors.",
    href: "/customizer?template=series",
    image: "/assets/projects/apple-tech-store.jpg",
    bgImage: "/assets/backgrounds/map.jpg",
    frameworks: [
      { id: 1, name: "Portrait" },
      { id: 2, name: "Detailed" },
      { id: 3, name: "Custom Fields" },
      { id: 4, name: "Auto-Sized" },
    ],
  },
  {
    id: 4,
    name: "Dark Edition",
    description: "All black premium collector aesthetic with subtle metallic accents. Sleek and sophisticated.",
    href: "/customizer?template=dark",
    image: "/assets/projects/electronics-store.jpg",
    bgImage: "/assets/backgrounds/poster.jpg",
    frameworks: [
      { id: 1, name: "Portrait" },
      { id: 2, name: "Premium" },
      { id: 3, name: "Custom Text" },
      { id: 4, name: "Auto-Sized" },
    ],
  },
  {
    id: 5,
    name: "Retro Style",
    description: "Vintage LEGO aesthetic with retro color palettes and classic typography. A nod to the golden era.",
    href: "/customizer?template=retro",
    image: "/assets/projects/home-decor-store.jpg",
    bgImage: "/assets/backgrounds/table.jpg",
    frameworks: [
      { id: 1, name: "Portrait" },
      { id: 2, name: "Retro" },
      { id: 3, name: "Custom Text" },
      { id: 4, name: "Auto-Sized" },
    ],
  },
  {
    id: 6,
    name: "Custom Creation",
    description: "Full creative control — upload your own artwork, set your own colors, and design from scratch.",
    href: "/customizer?template=custom",
    image: "/assets/projects/game-store.jpg",
    bgImage: "/assets/backgrounds/curtains.jpg",
    frameworks: [
      { id: 1, name: "Portrait" },
      { id: 2, name: "Full Custom" },
      { id: 3, name: "Image Upload" },
      { id: 4, name: "Any Size" },
    ],
  },
];
